### ISSUE TITLE
How do the file name / module name mapping rules work?

### ISSUE THREAD

**Issue by maasha** [JuliaLang/Example.jl#20]
Apparently the root level name `~/Example.jl` is case-insensitive and the `.jl` suffix is optional i.e. if I rename `~/Example.jl` to `~/example` it still works.

Changing `~/Example.jl` to `~/fobar` and it breaks.

However, `~/Example.jl/src/Example.jl` is not case-insensitive and the `.jl` suffix is mandatory ...

**Comment by yuyichao** [comment]
Please use `julia-users` for questions and if you are seeing case insensitivity with `using` or `import` on a case insensitive file system on 0.5/master please report it to base julia.
