### ISSUE TITLE
Project is in pre-Pkg3 format

### ISSUE THREAD

**Issue by pbouffard** [JuliaLang/Example.jl#36]
It seems hard to find Julia package repos that were created from scratch using Pkg3, which could be very useful when trying to diagnose problems one is having with creating such projects.

I'm happy to contribute a branch and PR for this; any reasons not to?

**Comment by nalimilan** [comment]
One issue is that currently the REQUIRE file is needed to register a package AFAIK. We should probably wait until the registries have been fully migrated to the new format.
