### ISSUE TITLE
Add Zenodo DOI

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/Example.jl#40]
Zenodo offers DOIs for released packages. See e.g. the DOI badge at <https://github.com/eschnett/FastArrays.jl> for an example.

It would be good if this package had an example for this. DOIs help make software citable.

Creating such DOIs is straightforward. Essentially, one adds the repo to Zenodo as one would for Travis or Appveyor <https://zenodo.org/account/settings/github/>, and Zenodo then tracks all releases made on Github and creates DOIs.

**Comment by samusz** [comment]
I don't see any DOI on [Julia](https://github.com/JuliaLang/julia)'s repo. 

Shouldn't it be more urgent than the Example.jl repo ?

**Comment by ViralBShah** [comment]
Happy to accept a PR. But not essential here.
