### ISSUE TITLE
How to deal with examples

### ISSUE THREAD

**Issue by freemin7** [JuliaLang/Example.jl#43]
Many Julia packages come with usage examples (for example https://github.com/denizyuret/Knet.jl/tree/master/examples ).
Would it be appropriate to add usage examples to the Example.jl?

**Comment by KristofferC** [comment]
There are a lot of different ways to do examples so it feels a bit out of scope for this package.

**Comment by freemin7** [comment]
I had problems finding a standard way to do it but maybe there is none.
