### ISSUE TITLE
Convert this to Template repository?

### ISSUE THREAD

**Issue by navidcy** [JuliaLang/Example.jl#62]
Just a suggestion...

**Comment by StefanKarpinski** [comment]
Can you elaborate? What does that mean?

**Comment by navidcy** [comment]
Sorry, I was a bit laconic. 

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository

**Comment by DilumAluthge** [comment]
I think this repo has some illustrative value, but I don't think it would make a good template repo.

Perhaps we can add a note in the README of this repo that links people to PkgTemplates.jl instead?

**Comment by navidcy** [comment]
I had forgotten about PkgTemplates.jl!

Feel free to close this.
