### ISSUE TITLE
Add the CompatHelper workflow to this example repo?

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/Example.jl#65]
I think the CompatHelper github workflow is important for packages that are setting `[compat]` bounds (which should be all packages, these days).
https://github.com/JuliaRegistries/CompatHelper.jl

Can we add the suggested CompatHelper workflow file to this repo?
CC: @DilumAluthge

**Comment by DilumAluthge** [comment]
Seems reasonable to me.

**Comment by NHDaly** [comment]
Thanks @DilumAluthge. Opened https://github.com/JuliaLang/Example.jl/pull/66 for this
