### ISSUE TITLE
Switch (or supplement) the macos github CI runner to aarch64

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/Example.jl#78]
https://github.com/JuliaLang/Example.jl/blob/63de11d03649f2fc86082a884d53670818af6f4b/.github/workflows/ci.yml#L24-L27

The aarch64 runners are available now:
https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

They should run tests faster.
Should we switch the CI.yml to use the new arm macs? or should it do both?

**Comment by NHDaly** [comment]
Although we noticed that it seems like GitHub uses an `arm64` image for _all_ the mac jobs, even if you specify `arch: x64`.......

Does anyone understand that? Is the arch field ignored?

CC @d-netto / @drvi

**Comment by ViralBShah** [comment]
This was fixed, I believe. Anyways, this is now doing the right thing.
